#!/bin/bash

if [ $# -eq 1 ]; then
    echo -e "Checking user activity on '$1':"
    username=$(whoami)
    query="SELECT DISTINCT ON (usename) datname,usename,now()-query_start AS duration,client_addr,waiting FROM pg_stat_activity
        WHERE usename <> 'mri_web'
        AND usename <> 'remote_app'
        ORDER BY usename, query_start ASC;"

    if [[ "$1" =~ ^(dev|test){1}-{1}(2|staging){1}-{1}(1|2|3|4){1}$ ]]; then
        psql -h $1 -d ppl -U $username -c "$query" -W
    elif [[ "$1" =~ ^(dev|test){1}-vault-{1}(1|2){1}$ ]]; then
        psql -h $1 -d wstatsw -U $username -c "$query" -W
    else
        echo -e "The instance '$1' does not exist."
    fi

else
    echo "There are no instances specified. There is only a limit of 1 parameter."
fi
