#!/bin/bash
if [ $# -eq 1 ]; then
  if [ "$1" = "--v6" ]; then
    ip a | cat | grep 'inet6 ' | cut -d ' ' -f 6
  else
    ip a | cat | grep 'inet ' | cut -d ' ' -f 6
  fi
else
  ip a | cat | grep 'inet ' | cut -d ' ' -f 6 
fi
